# @package dataset
# ImpactPlate dataset configuration

root: ./dataset_public/impact_plate
window_size: 51
window_shift: 51
val_window_size: 51
val_window_shift: 51
train_n_sequences: null
val_n_sequences: null
shuffle: True
pin_memory: True
