# @package env
# SphereCloth environment configuration

name: "SphereClothCouplingEnv"
input_keys: ["PROPERTIES", "STATE", "STATE_DOT"]
output_keys: ["STATE", "STATE_DOT"]
# Whether to use sparse connections between the sphere and cloth particles. 
# If True, only connect the sphere to the corners of the cloth,
# otherwise, every fourth particle is connected to the sphere.
sparse_connections: False  
ignore_n_initial_steps: 0
training_noise: ${training_noise}
training_noise_std: ${training_noise_std}
visualizer:
  plot_elev: 30
  plot_azim: -60
  n_columns: 3
  overlayed_ground_truth: False
